# Generated by Django 4.1.3 on 2025-06-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, default='', editable=False, unique=True)),
                ('description', models.TextField(blank=True)),
                ('images', models.ImageField(upload_to='images/')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('isActive', models.BooleanField()),
                ('categories', models.ManyToManyField(to='main.category')),
            ],
        ),
    ]
